### ISSUE TITLE
MenuController.dataMap: Use ArrayList instead of HashMap

### ISSUE THREAD

**Issue by 173210** [arc218/Launcher#3]
The integer value can be used as the number of array element.
https://github.com/arc218/Launcher/commit/f32e3207f9500c36c53c510174509e5ba09cc382#diff-bde5c54378311c57841ce7c129cd54b4R63
```
	private HashMap<Integer, HashMap<String, String>> dataMap;
```

**Comment by arc218** [comment]
d2b859f00a2718803c33137389c3cc65f989558c で完了
